/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corbacliente.ventanas;

import corbacliente.CustomListModel;
import corbacliente.Interfaz;
import corbacliente.Persona;
import javax.swing.JOptionPane;
import utility.Utility;

/**
 *
 * @author Oriana
 */
public class Clientes extends javax.swing.JFrame {

    public static CustomListModel list_model = new CustomListModel();
    public static String cliente;
    public static int selectedIndex; 

    /**
     * Creates new form Cliente
     */
    public Clientes() {
        initComponents();
        clientes.setModel(list_model);
        Utility utility = new Utility(this);
        utility.centerOnScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_asignarCliente = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_cedula = new javax.swing.JLabel();
        fld_nombre = new javax.swing.JTextField();
        fld_cedula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientes = new javax.swing.JList<>();
        lbl_clientes = new javax.swing.JLabel();
        b_atras = new javax.swing.JButton();
        b_aceptar = new javax.swing.JButton();
        lbl_cedula1 = new javax.swing.JLabel();
        fld_direccion = new javax.swing.JTextField();
        lbl_informacion_nombre = new javax.swing.JLabel();
        lbl_info_nombre = new javax.swing.JLabel();
        lbl_informacion_direccion = new javax.swing.JLabel();
        lbl_informacion_cedula = new javax.swing.JLabel();
        lbl_info_cedula = new javax.swing.JLabel();
        lbl_info_direccion = new javax.swing.JLabel();
        b_anadir = new javax.swing.JButton();
        b_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_asignarCliente.setText("Asignar Cliente");

        lbl_nombre.setText("Nombre:");

        lbl_cedula.setText("Cedula:");

        fld_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_nombreActionPerformed(evt);
            }
        });

        fld_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_cedulaActionPerformed(evt);
            }
        });

        clientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                clientesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(clientes);

        lbl_clientes.setText("Clientes:");

        b_atras.setText("Atrás");
        b_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_atrasActionPerformed(evt);
            }
        });

        b_aceptar.setText("Confirmar");
        b_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aceptarActionPerformed(evt);
            }
        });

        lbl_cedula1.setText("Direccion:");

        fld_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_direccionActionPerformed(evt);
            }
        });

        lbl_informacion_nombre.setText("Nombre:");

        lbl_informacion_direccion.setText("Direccion:");

        lbl_informacion_cedula.setText("Cedula:");

        b_anadir.setText("+");
        b_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_anadirActionPerformed(evt);
            }
        });

        b_eliminar.setText("-");
        b_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_cedula1)
                        .addGap(18, 18, 18)
                        .addComponent(fld_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addGap(82, 82, 82)
                        .addComponent(b_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_anadir)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_informacion_nombre)
                            .addComponent(lbl_informacion_direccion)
                            .addComponent(lbl_informacion_cedula))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_info_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_info_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl_info_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_asignarCliente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_clientes)
                            .addGap(37, 37, 37))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_nombre)
                                .addComponent(lbl_cedula))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fld_cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(fld_nombre))
                            .addGap(62, 62, 62)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(b_aceptar))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(b_atras)
                            .addGap(352, 352, 352)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fld_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cedula1)
                    .addComponent(b_anadir)
                    .addComponent(b_eliminar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_informacion_nombre)
                    .addComponent(lbl_info_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_informacion_cedula)
                    .addComponent(lbl_info_cedula))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_informacion_direccion)
                    .addComponent(lbl_info_direccion))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_asignarCliente)
                        .addComponent(lbl_clientes))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_nombre)
                                .addComponent(fld_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_cedula)
                                .addComponent(fld_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(158, 158, 158)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_atras)
                        .addComponent(b_aceptar))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fld_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_nombreActionPerformed

    private void fld_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_cedulaActionPerformed

    private void clientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_clientesValueChanged

        mostrarPersona();
    }//GEN-LAST:event_clientesValueChanged

    private void b_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_atrasActionPerformed
        limpiarClientes();
        this.setVisible(false);
        Interfaz.getInterfaz(0).setVisible(true);
    }//GEN-LAST:event_b_atrasActionPerformed

    private void b_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aceptarActionPerformed
        selectedIndex = clientes.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(null, "Ingrese un cliente");
        } else {
            Persona p = list_model.getPersona(selectedIndex);
            System.out.println("Persona seleccionada al final: " + p.getNombre());
            cliente = p.getNombre();
            this.setVisible(false);
            Interfaz.getInterfaz(2).setVisible(true);
        }


    }//GEN-LAST:event_b_aceptarActionPerformed

    private void fld_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_direccionActionPerformed

    private void b_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_anadirActionPerformed
        Persona p = new Persona(fld_nombre.getText(), fld_cedula.getText(), fld_direccion.getText());
        list_model.add(p);
    }//GEN-LAST:event_b_anadirActionPerformed

    private void b_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eliminarActionPerformed
        selectedIndex = clientes.getSelectedIndex();
        if (selectedIndex != -1) {
            list_model.delete(selectedIndex);
        }
    }//GEN-LAST:event_b_eliminarActionPerformed

    private void limpiarClientes() {
        lbl_info_nombre.setText("");
        lbl_info_cedula.setText("");
        lbl_info_direccion.setText("");
        fld_nombre.setText("");
        fld_cedula.setText("");
        fld_direccion.setText("");
    }

    private void mostrarPersona() {
        selectedIndex = clientes.getSelectedIndex();
        if (selectedIndex != -1) {
            Persona p = list_model.getPersona(selectedIndex);
            lbl_info_nombre.setText(p.getNombre());
            lbl_info_cedula.setText(p.getCedula());
            lbl_info_direccion.setText(p.getDireccion());

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_aceptar;
    private javax.swing.JButton b_anadir;
    private javax.swing.JButton b_atras;
    private javax.swing.JButton b_eliminar;
    private javax.swing.JList<String> clientes;
    private javax.swing.JTextField fld_cedula;
    private javax.swing.JTextField fld_direccion;
    private javax.swing.JTextField fld_nombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_asignarCliente;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_cedula1;
    private javax.swing.JLabel lbl_clientes;
    private javax.swing.JLabel lbl_info_cedula;
    private javax.swing.JLabel lbl_info_direccion;
    private javax.swing.JLabel lbl_info_nombre;
    private javax.swing.JLabel lbl_informacion_cedula;
    private javax.swing.JLabel lbl_informacion_direccion;
    private javax.swing.JLabel lbl_informacion_nombre;
    private javax.swing.JLabel lbl_nombre;
    // End of variables declaration//GEN-END:variables
}
