/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corbacliente.ventanas;

import corbacliente.CustomListModel;
import corbacliente.Interfaz;
import corbacliente.Persona;
import utility.Utility;

/**
 *
 * @author Oriana
 */
public class ProductosV extends javax.swing.JFrame {

    public static CustomListModel list_model = new CustomListModel();

    /**
     * Creates new form CrearFactura
     */
    public ProductosV() {
        initComponents();
        productos.setModel(list_model);
        Utility utility = new Utility(this);
        utility.centerOnScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondo = new javax.swing.JPanel();
        lbl_agregarProductos = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_precio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productos = new javax.swing.JList<>();
        b_anadir = new javax.swing.JButton();
        fld_nombre = new javax.swing.JTextField();
        fld_precio = new javax.swing.JTextField();
        lbl_productos = new javax.swing.JLabel();
        b_eliminar = new javax.swing.JButton();
        lbl_informacion_nombre = new javax.swing.JLabel();
        lbl_informacion_precio = new javax.swing.JLabel();
        lbl_info_nombre = new javax.swing.JLabel();
        lbl_info_precio = new javax.swing.JLabel();
        b_atras = new javax.swing.JButton();
        b_aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_agregarProductos.setText("Agregar productos");

        lbl_nombre.setText("Nombre:");

        lbl_precio.setText("Precio:");

        productos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                productosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(productos);

        b_anadir.setText("+");
        b_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_anadirActionPerformed(evt);
            }
        });

        fld_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_nombreActionPerformed(evt);
            }
        });

        fld_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_precioActionPerformed(evt);
            }
        });

        lbl_productos.setText("Productos:");

        b_eliminar.setText("-");
        b_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eliminarActionPerformed(evt);
            }
        });

        lbl_informacion_nombre.setText("Nombre:");

        lbl_informacion_precio.setText("Precio:");

        b_atras.setText("Atrás");
        b_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_atrasActionPerformed(evt);
            }
        });

        b_aceptar.setText("Confirmar");
        b_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fondoLayout = new javax.swing.GroupLayout(panel_fondo);
        panel_fondo.setLayout(panel_fondoLayout);
        panel_fondoLayout.setHorizontalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_fondoLayout.createSequentialGroup()
                                .addComponent(lbl_agregarProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_productos)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_fondoLayout.createSequentialGroup()
                                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_nombre)
                                    .addComponent(lbl_precio)
                                    .addComponent(lbl_informacion_nombre))
                                .addGap(26, 26, 26)
                                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fld_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(fld_nombre)
                                    .addComponent(lbl_info_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(lbl_info_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(62, 62, 62)
                                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(panel_fondoLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(b_aceptar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(b_eliminar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(b_anadir)
                                        .addGap(26, 26, 26)))))
                        .addGap(7, 7, 7))
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_informacion_precio)
                            .addComponent(b_atras))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panel_fondoLayout.setVerticalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_agregarProductos)
                    .addComponent(lbl_productos))
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre)
                            .addComponent(fld_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_precio)
                            .addComponent(fld_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_anadir)
                    .addComponent(b_eliminar))
                .addGap(39, 39, 39)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_informacion_nombre)
                    .addComponent(lbl_info_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_informacion_precio)
                    .addComponent(lbl_info_precio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_atras)
                    .addComponent(b_aceptar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_anadirActionPerformed
        float precio = Float.parseFloat(fld_precio.getText());
        corbacliente.Productos p = new corbacliente.Productos(fld_nombre.getText(), precio);
        list_model.add(p);
    }//GEN-LAST:event_b_anadirActionPerformed

    private void fld_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_nombreActionPerformed

    private void fld_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_precioActionPerformed

    private void b_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eliminarActionPerformed
        int selection = productos.getSelectedIndex();
        if (selection != -1) {
            list_model.delete(selection);
        }
    }//GEN-LAST:event_b_eliminarActionPerformed

    private void productosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_productosValueChanged

        mostrarProducto();
    }//GEN-LAST:event_productosValueChanged

    private void b_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_atrasActionPerformed
        limpiarProductos();
        this.setVisible(false);
        Interfaz.getInterfaz(1).setVisible(true);

    }//GEN-LAST:event_b_atrasActionPerformed

    private void b_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aceptarActionPerformed
        this.setVisible(false);
        Interfaz.getInterfaz(0).setVisible(true);
    }//GEN-LAST:event_b_aceptarActionPerformed

    private void mostrarProducto() {
        int selection = productos.getSelectedIndex();
        if (selection != -1) {
            corbacliente.Productos p = list_model.getProducto(selection);
            lbl_info_nombre.setText(p.getNombre());
            lbl_info_precio.setText(Float.toString(p.getPrecio()));

        }
    }

    private void limpiarProductos(){
        lbl_info_nombre.setText("");
        lbl_info_precio.setText("");
        fld_nombre.setText("");
        fld_precio.setText("");
        list_model.removeAll();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductosV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_aceptar;
    private javax.swing.JButton b_anadir;
    private javax.swing.JButton b_atras;
    private javax.swing.JButton b_eliminar;
    private javax.swing.JTextField fld_nombre;
    private javax.swing.JTextField fld_precio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_agregarProductos;
    private javax.swing.JLabel lbl_info_nombre;
    private javax.swing.JLabel lbl_info_precio;
    private javax.swing.JLabel lbl_informacion_nombre;
    private javax.swing.JLabel lbl_informacion_precio;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JLabel lbl_productos;
    private javax.swing.JPanel panel_fondo;
    private javax.swing.JList<String> productos;
    // End of variables declaration//GEN-END:variables
}
