module manejadores{ 
    
    struct Productos{
        string nombre;
        float precio;
    };

    typedef sequence<Productos> productosarray;

    interface factura{ 

        void generar(in string nombre, in string cedula, in string direccionp, in productosarray productos, in string company, in string direccionc, in string telefono, in long numero);
        
    }; 
};
