module manejadores{ 
    
    struct Productos{
        string nombre;
        float pecio;
    };

    typedef sequence <Productos> productoss;

    interface factura{ 
        
        void generar(in string nombre, in string cedula, in string direccionp, in productoss productos, in string company, in string direccionc, in string telefono, in long numero);
        
    }; 
};
