package manejadores;


/**
* manejadores/facturaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Oriana/Documents/NetBeansProjects/Corba/CorbaInterface/src/corbainterface/generar.idl
* Tuesday, May 28, 2019 3:34:39 AM VET
*/

public interface facturaOperations 
{

  /*
         * Para generar 
         * in: el valor del parametro se lo envia el cliente al servidor
         * long: -231..231-1 (32 bits)
         * numero: nombre de la variable
        */
  String generar (int numero);
} // interface facturaOperations
