package manejadores;


/**
* manejadores/facturaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Oriana/Documents/NetBeansProjects/Corba/CorbaInterface/src/corbainterface/generar.idl
* Tuesday, May 28, 2019 3:34:39 AM VET
*/

abstract public class facturaHelper
{
  private static String  _id = "IDL:manejadores/factura:1.0";

  public static void insert (org.omg.CORBA.Any a, manejadores.factura that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static manejadores.factura extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (manejadores.facturaHelper.id (), "factura");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static manejadores.factura read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_facturaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, manejadores.factura value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static manejadores.factura narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof manejadores.factura)
      return (manejadores.factura)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      manejadores._facturaStub stub = new manejadores._facturaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static manejadores.factura unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof manejadores.factura)
      return (manejadores.factura)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      manejadores._facturaStub stub = new manejadores._facturaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
