package manejadores;

/**
* manejadores/facturaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/LABAM/Documents/Parra/Sistemas Distribuidos/CORBA/CORBA/CorbaInterface/src/corbainterface/generar.idl
* martes 28 de mayo de 2019 15H59' PYT
*/

public final class facturaHolder implements org.omg.CORBA.portable.Streamable
{
  public manejadores.factura value = null;

  public facturaHolder ()
  {
  }

  public facturaHolder (manejadores.factura initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = manejadores.facturaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    manejadores.facturaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return manejadores.facturaHelper.type ();
  }

}
