package manejadores;


/**
* manejadores/facturaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/LABAM/Documents/Parra/Sistemas Distribuidos/CORBA/CORBA/CorbaInterface/src/corbainterface/generar.idl
* martes 28 de mayo de 2019 14H59' PYT
*/

public abstract class facturaPOA extends org.omg.PortableServer.Servant
 implements manejadores.facturaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("generar", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // manejadores/factura/generar
       {
         String nombre = in.read_string ();
         String cedula = in.read_string ();
         String direccionp = in.read_string ();
         manejadores.Productos productos[] = manejadores.productossHelper.read (in);
         String company = in.read_string ();
         String direccionc = in.read_string ();
         String telefono = in.read_string ();
         int numero = in.read_long ();
         this.generar (nombre, cedula, direccionp, productos, company, direccionc, telefono, numero);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:manejadores/factura:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public factura _this() 
  {
    return facturaHelper.narrow(
    super._this_object());
  }

  public factura _this(org.omg.CORBA.ORB orb) 
  {
    return facturaHelper.narrow(
    super._this_object(orb));
  }


} // class facturaPOA
