package manejadores;



/**
* manejadores/factura.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/LABAM/Documents/Parra/Sistemas Distribuidos/CORBA/CORBA/CorbaInterface/src/corbainterface/generar.idl
* martes 28 de mayo de 2019 15H59' PYT
*/

public interface factura extends facturaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface factura
