package manejadores;


/**
* manejadores/factura.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Oriana/Documents/NetBeansProjects/Corba/CorbaInterface/src/corbainterface/generar.idl
* Tuesday, May 28, 2019 3:34:39 AM VET
*/

public interface factura extends facturaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface factura
