package manejadores;

/**
* manejadores/facturaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Oriana/Documents/NetBeansProjects/Corba/CorbaInterface/src/corbainterface/generar.idl
* Tuesday, May 28, 2019 3:34:39 AM VET
*/

public final class facturaHolder implements org.omg.CORBA.portable.Streamable
{
  public manejadores.factura value = null;

  public facturaHolder ()
  {
  }

  public facturaHolder (manejadores.factura initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = manejadores.facturaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    manejadores.facturaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return manejadores.facturaHelper.type ();
  }

}
