package manejadores;


/**
* manejadores/Productos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/LABAM/Documents/Parra/Sistemas Distribuidos/CORBA/CORBA/CorbaInterface/src/corbainterface/generar.idl
* martes 28 de mayo de 2019 15H59' PYT
*/

public final class Productos implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public float precio = (float)0;

  public Productos ()
  {
  } // ctor

  public Productos (String _nombre, float _precio)
  {
    nombre = _nombre;
    precio = _precio;
  } // ctor

} // class Productos
