package example;


/**
* example/fibonacci.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Oriana/Documents/NetBeansProjects/Corba/CorbaInterface/src/corbainterface/fibonacci.idl
* Monday, May 27, 2019 9:01:58 PM VET
*/

public interface fibonacci extends fibonacciOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface fibonacci
