package example;


/**
* example/fibonacciOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Oriana/Documents/NetBeansProjects/Corba/CorbaInterface/src/corbainterface/fibonacci.idl
* Monday, May 27, 2019 9:01:58 PM VET
*/

public interface fibonacciOperations 
{

  /*
         * Para generar 
         * in: el valor del parametro se lo envia el cliente al servidor
         * long: -231..231-1 (32 bits)
         * numero: nombre de la variable
        */
  String generar (int numero);
} // interface fibonacciOperations
